apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-test
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: java-test
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/jgalvin98/java-test.git
      ref:
        branch: main
